// FMTRX Exercise Library
//
// This is the normalized strength/performance library that feeds the Daily
// Planner. The app already has the bucket model; this file classifies exercises
// so future intelligence can connect workout choices to physical qualities.

const slug = (value) =>
  String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');

const asArray = (value) => Array.isArray(value) ? value : [value].filter(Boolean);

const exercise = (group, defaults, name, overrides = {}) => {
  const bucket = overrides.bucket || defaults.bucket;
  const subcategory = overrides.subcategory || defaults.subcategory || group;
  const physicalQualities = overrides.physicalQualities || defaults.physicalQualities || [];
  const baseballCorrelations = overrides.baseballCorrelations || defaults.baseballCorrelations || [];

  return {
    id: overrides.id || `ex_${slug(bucket)}_${slug(group)}_${slug(name)}`,
    name,
    bucket,
    categoryGroup: group,
    subcategory,
    description: overrides.description || defaults.description || '',
    equipment: overrides.equipment || defaults.equipment || '',
    defaultSets: overrides.defaultSets ?? defaults.defaultSets ?? null,
    defaultReps: overrides.defaultReps ?? defaults.defaultReps ?? null,
    defaultDurationSec: overrides.defaultDurationSec ?? defaults.defaultDurationSec ?? null,
    defaultDistance: overrides.defaultDistance ?? defaults.defaultDistance ?? null,
    defaultThrows: overrides.defaultThrows ?? defaults.defaultThrows ?? null,
    defaultIntensity: overrides.defaultIntensity || defaults.defaultIntensity || 'Moderate',
    defaultIntent: overrides.defaultIntent ?? defaults.defaultIntent ?? null,
    workloadType: overrides.workloadType || defaults.workloadType || 'strength',
    bodyRegion: overrides.bodyRegion || defaults.bodyRegion || '',
    movementPattern: overrides.movementPattern || defaults.movementPattern || subcategory,
    physicalQuality: overrides.physicalQuality || defaults.physicalQuality || physicalQualities[0] || '',
    physicalQualities,
    baseballCorrelation: overrides.baseballCorrelation || defaults.baseballCorrelation || baseballCorrelations[0] || '',
    baseballCorrelations,
    relatedMetrics: overrides.relatedMetrics || defaults.relatedMetrics || [],
    tags: [
      ...asArray(defaults.tags),
      ...asArray(overrides.tags),
      group.toLowerCase(),
      subcategory.toLowerCase(),
    ].filter(Boolean),
    coachCue: overrides.coachCue || defaults.coachCue || '',
    source: 'exercise_library',
  };
};

const group = (name, defaults, items) =>
  items.map((item) => Array.isArray(item)
    ? exercise(name, defaults, item[0], item[1] || {})
    : exercise(name, defaults, item));

export const EXERCISE_LIBRARY = [
  ...group('Lower Body Strength', {
    bucket: 'strength',
    subcategory: 'Bilateral Squat',
    bodyRegion: 'Lower Body',
    movementPattern: 'Squat',
    physicalQualities: ['Max Force', 'Lower Body Strength'],
    baseballCorrelations: ['Pitch Velocity', 'Exit Velocity', 'Lower Body Force Production'],
    relatedMetrics: ['squat', 'strength_score', 'exit_velocity', 'pitch_velocity'],
    equipment: 'Barbell or rack',
    defaultSets: 4,
    defaultReps: 5,
    defaultIntensity: 'High',
  }, [
    'Back Squat',
    'Front Squat',
    'Safety Bar Squat',
    'Box Squat',
    ['Goblet Squat', { equipment: 'Dumbbell or kettlebell', defaultSets: 3, defaultReps: 8, defaultIntensity: 'Moderate' }],
    'Belt Squat',
    'Zercher Squat',
    ['Bulgarian Split Squat', { subcategory: 'Single Leg Squat', movementPattern: 'Unilateral Squat', defaultSets: 3, defaultReps: 8 }],
    ['Rear Foot Elevated Split Squat', { subcategory: 'Single Leg Squat', movementPattern: 'Unilateral Squat', defaultSets: 3, defaultReps: 8 }],
    ['Split Squat', { subcategory: 'Single Leg Squat', movementPattern: 'Unilateral Squat', defaultSets: 3, defaultReps: 8 }],
    ['Walking Lunge', { subcategory: 'Single Leg Squat', movementPattern: 'Lunge', equipment: 'Dumbbells optional', defaultSets: 3, defaultReps: 10 }],
    ['Reverse Lunge', { subcategory: 'Single Leg Squat', movementPattern: 'Lunge', equipment: 'Dumbbells optional', defaultSets: 3, defaultReps: 8 }],
    ['Lateral Lunge', { subcategory: 'Single Leg Squat', movementPattern: 'Lateral Lunge', equipment: 'Dumbbells optional', defaultSets: 3, defaultReps: 8 }],
    ['Cossack Squat', { subcategory: 'Single Leg Squat', movementPattern: 'Lateral Squat', equipment: 'Bodyweight or kettlebell', defaultSets: 3, defaultReps: 6 }],
    ['Step Ups', { subcategory: 'Single Leg Squat', movementPattern: 'Step Up', equipment: 'Box, dumbbells optional', defaultSets: 3, defaultReps: 8 }],
    ['Single Leg Squat (Pistol)', { subcategory: 'Single Leg Squat', movementPattern: 'Unilateral Squat', equipment: 'Bodyweight', defaultSets: 3, defaultReps: 5 }],
  ]),

  ...group('Hip Hinge / Posterior Chain', {
    bucket: 'strength',
    subcategory: 'Hip Hinge',
    bodyRegion: 'Posterior Chain',
    movementPattern: 'Hinge',
    physicalQualities: ['Posterior Chain Strength', 'Hip Extension Force'],
    baseballCorrelations: ['Pitch Velocity', 'Exit Velocity', 'Acceleration'],
    relatedMetrics: ['deadlift', 'strength_score', 'pitch_velocity', 'exit_velocity'],
    equipment: 'Barbell or trap bar',
    defaultSets: 4,
    defaultReps: 5,
    defaultIntensity: 'High',
  }, [
    'Trap Bar Deadlift',
    'Conventional Deadlift',
    'Sumo Deadlift',
    ['Romanian Deadlift', { defaultSets: 3, defaultReps: 8, defaultIntensity: 'Moderate' }],
    ['Single Leg RDL', { movementPattern: 'Single Leg Hinge', equipment: 'Dumbbells optional', defaultSets: 3, defaultReps: 8, defaultIntensity: 'Moderate' }],
    ['Stiff Leg Deadlift', { defaultSets: 3, defaultReps: 8, defaultIntensity: 'Moderate' }],
    'Rack Pull',
    ['Good Morning', { defaultSets: 3, defaultReps: 8, defaultIntensity: 'Moderate' }],
    ['Hip Thrust', { movementPattern: 'Hip Extension', defaultSets: 3, defaultReps: 8 }],
    ['Barbell Glute Bridge', { movementPattern: 'Hip Extension', defaultSets: 3, defaultReps: 8 }],
    ['Nordic Hamstring Curl', { movementPattern: 'Knee Flexion', equipment: 'Nordic bench or partner', defaultSets: 3, defaultReps: 5 }],
    ['GHD Raise', { movementPattern: 'Knee Flexion', equipment: 'GHD', defaultSets: 3, defaultReps: 8 }],
  ]),

  ...group('Olympic Power', {
    bucket: 'strength',
    subcategory: 'Olympic Power',
    bodyRegion: 'Total Body',
    movementPattern: 'Triple Extension',
    physicalQualities: ['Explosive Power', 'Rate of Force Development'],
    baseballCorrelations: ['Arm Speed', 'Exit Velocity', 'Rotational Force'],
    relatedMetrics: ['power_clean', 'vertical_jump', 'broad_jump', 'pitch_velocity', 'exit_velocity'],
    equipment: 'Barbell',
    defaultSets: 4,
    defaultReps: 3,
    defaultIntensity: 'High',
  }, [
    'Power Clean',
    'Hang Clean',
    'Clean Pull',
    'High Pull',
    'Power Snatch',
    'Hang Snatch',
    'Snatch Pull',
    'Push Press',
    'Push Jerk',
    'Split Jerk',
    ['Jump Shrugs', { defaultSets: 3, defaultReps: 5 }],
  ]),

  ...group('Upper Body Push', {
    bucket: 'strength',
    subcategory: 'Horizontal Push',
    bodyRegion: 'Upper Body',
    movementPattern: 'Push',
    physicalQualities: ['Upper Body Strength', 'Pressing Strength'],
    baseballCorrelations: ['Exit Velocity', 'Physical Robustness'],
    relatedMetrics: ['bench_press', 'pushups', 'strength_score'],
    equipment: 'Barbell or dumbbells',
    defaultSets: 4,
    defaultReps: 6,
    defaultIntensity: 'Moderate',
  }, [
    'Bench Press',
    'Incline Bench',
    'Decline Bench',
    'Floor Press',
    'Dumbbell Bench',
    ['Push Ups', { equipment: 'Bodyweight', relatedMetrics: ['pushups', 'strength_score'], defaultSets: 3, defaultReps: 12 }],
    'Close Grip Bench',
    ['Military Press', { subcategory: 'Vertical Push', movementPattern: 'Vertical Push' }],
    ['Shoulder Press', { subcategory: 'Vertical Push', movementPattern: 'Vertical Push' }],
    ['Dumbbell Press', { subcategory: 'Vertical Push', movementPattern: 'Vertical Push' }],
    ['Landmine Press', { subcategory: 'Vertical Push', movementPattern: 'Angled Push', equipment: 'Landmine' }],
    ['Arnold Press', { subcategory: 'Vertical Push', movementPattern: 'Vertical Push', equipment: 'Dumbbells' }],
  ]),

  ...group('Upper Body Pull', {
    bucket: 'strength',
    subcategory: 'Vertical Pull',
    bodyRegion: 'Upper Body',
    movementPattern: 'Pull',
    physicalQualities: ['Relative Strength', 'Scapular Strength'],
    baseballCorrelations: ['Scapular Stability', 'Arm Health'],
    relatedMetrics: ['pull_ups', 'strength_score'],
    equipment: 'Pull-up bar or cable',
    defaultSets: 3,
    defaultReps: 8,
    defaultIntensity: 'Moderate',
  }, [
    'Pull Ups',
    'Chin Ups',
    'Neutral Grip Pull Ups',
    ['Weighted Pull Ups', { defaultReps: 5, defaultIntensity: 'High' }],
    'Lat Pulldown',
    ['Bent Over Row', { subcategory: 'Horizontal Pull', movementPattern: 'Horizontal Pull', equipment: 'Barbell' }],
    ['Chest Supported Row', { subcategory: 'Horizontal Pull', movementPattern: 'Horizontal Pull' }],
    ['Cable Row', { subcategory: 'Horizontal Pull', movementPattern: 'Horizontal Pull', equipment: 'Cable' }],
    ['One Arm DB Row', { subcategory: 'Horizontal Pull', movementPattern: 'Horizontal Pull', equipment: 'Dumbbell' }],
    ['Seal Row', { subcategory: 'Horizontal Pull', movementPattern: 'Horizontal Pull' }],
    ['TRX Row', { subcategory: 'Horizontal Pull', movementPattern: 'Horizontal Pull', equipment: 'TRX' }],
    ['Inverted Row', { subcategory: 'Horizontal Pull', movementPattern: 'Horizontal Pull', equipment: 'Bar or rings' }],
  ]),

  ...group('Shoulder Health', {
    bucket: 'arm_care',
    subcategory: 'Scapular Control',
    bodyRegion: 'Shoulder',
    movementPattern: 'Scapular Stability',
    physicalQualities: ['Shoulder Stability', 'Scapular Control'],
    baseballCorrelations: ['Arm Health', 'Throwing Availability'],
    relatedMetrics: ['arm_care_compliance', 'shoulder_mobility_score'],
    equipment: 'Bands or light dumbbells',
    defaultSets: 2,
    defaultReps: 12,
    defaultIntensity: 'Low',
    workloadType: 'reps',
  }, [
    'Face Pull',
    'Cuban Press',
    'Y Raises',
    'T Raises',
    'W Raises',
    'I Raises',
    'Serratus Punch',
    'Blackburn Series',
    'Scap Push Ups',
    'Wall Slides',
  ]),

  ...group('Rotator Cuff', {
    bucket: 'arm_care',
    subcategory: 'Rotator Cuff',
    bodyRegion: 'Shoulder',
    movementPattern: 'Internal / External Rotation',
    physicalQualities: ['Cuff Strength', 'Shoulder Stability'],
    baseballCorrelations: ['Injury Prevention', 'Throwing Readiness'],
    relatedMetrics: ['arm_care_compliance', 'shoulder_mobility_score'],
    equipment: 'Bands or light dumbbells',
    defaultSets: 2,
    defaultReps: 12,
    defaultIntensity: 'Low',
    workloadType: 'reps',
  }, [
    'External Rotation',
    'Internal Rotation',
    'Band ER',
    'Band IR',
    'Side Lying ER',
    '90/90 ER',
    '90/90 IR',
    "Thrower's Ten",
    'J-Bands',
    'Bodyblade',
  ]),

  ...group('Core Stability', {
    bucket: 'strength',
    subcategory: 'Anti-Rotation',
    bodyRegion: 'Core',
    movementPattern: 'Core Stability',
    physicalQualities: ['Trunk Stability', 'Force Transfer'],
    baseballCorrelations: ['Rotational Force', 'Pitch Command', 'Swing Direction'],
    relatedMetrics: ['rotational_power_score', 'strength_score'],
    equipment: 'Bodyweight, cable, or med ball',
    defaultSets: 3,
    defaultReps: 10,
    defaultIntensity: 'Moderate',
  }, [
    'Pallof Press',
    'Dead Bug',
    'Bird Dog',
    ['Russian Twist', { subcategory: 'Rotation', movementPattern: 'Trunk Rotation' }],
    ['Cable Rotation', { subcategory: 'Rotation', movementPattern: 'Trunk Rotation', equipment: 'Cable' }],
    ['Landmine Rotation', { subcategory: 'Rotation', movementPattern: 'Trunk Rotation', equipment: 'Landmine' }],
    ['Sit Ups', { subcategory: 'Flexion', movementPattern: 'Trunk Flexion' }],
    ['Hanging Leg Raise', { subcategory: 'Flexion', movementPattern: 'Trunk Flexion', equipment: 'Pull-up bar' }],
    ['Ab Wheel', { subcategory: 'Flexion', movementPattern: 'Anti-Extension', equipment: 'Ab wheel' }],
    ['V Ups', { subcategory: 'Flexion', movementPattern: 'Trunk Flexion' }],
    ['Front Plank', { subcategory: 'Stability', movementPattern: 'Anti-Extension', defaultDurationSec: 45, defaultReps: null }],
    ['Side Plank', { subcategory: 'Stability', movementPattern: 'Lateral Stability', defaultDurationSec: 30, defaultReps: null }],
    ['Copenhagen Plank', { subcategory: 'Stability', movementPattern: 'Adductor Stability', defaultDurationSec: 25, defaultReps: null }],
    ['Hollow Hold', { subcategory: 'Stability', movementPattern: 'Anti-Extension', defaultDurationSec: 30, defaultReps: null }],
  ]),

  ...group('Rotational Power', {
    bucket: 'strength',
    subcategory: 'Rotational Power',
    bodyRegion: 'Total Body',
    movementPattern: 'Rotation',
    physicalQualities: ['Rotational Power', 'Power Transfer'],
    baseballCorrelations: ['Exit Velocity', 'Pitch Velocity'],
    relatedMetrics: ['rotational_power_score', 'exit_velocity', 'pitch_velocity'],
    equipment: 'Medicine ball',
    defaultSets: 3,
    defaultReps: 5,
    defaultIntensity: 'High',
  }, [
    'Rotational Scoop Toss',
    'Step Behind Scoop Toss',
    'Shotput Throw',
    'Side Toss',
    'Kneeling Rotational Throw',
    'Half Kneeling Throw',
    'Overhead Slam',
    'Chest Pass',
    'Overhead Back Toss',
  ]),

  ...group('Lower Body Power', {
    bucket: 'strength',
    subcategory: 'Lower Body Power',
    bodyRegion: 'Lower Body',
    movementPattern: 'Jump',
    physicalQualities: ['Explosive Power', 'Elasticity'],
    baseballCorrelations: ['Sprint Speed', 'Rotational Force', 'Pitch Velocity'],
    relatedMetrics: ['vertical_jump', 'broad_jump', 'forty_yard_dash', 'sixty_yard_dash'],
    equipment: 'Turf or box',
    defaultSets: 3,
    defaultReps: 5,
    defaultIntensity: 'High',
  }, [
    'Vertical Jump',
    'Broad Jump',
    'Triple Broad Jump',
    'Single Leg Broad Jump',
    'Reactive Jump',
    'Box Jump',
    'Depth Jump',
    'Drop Jump',
    'Countermovement Jump',
    'Skater Jump',
  ]),

  ...group('Speed', {
    bucket: 'speed_agility',
    subcategory: 'Speed',
    bodyRegion: 'Full Body',
    movementPattern: 'Sprint',
    physicalQualities: ['Acceleration', 'Top Speed'],
    baseballCorrelations: ['Baserunning', 'Range', 'Athleticism'],
    relatedMetrics: ['forty_yard_dash', 'sixty_yard_dash'],
    equipment: 'Turf, cones, stopwatch',
    defaultSets: 4,
    defaultReps: 1,
    defaultIntensity: 'High',
    workloadType: 'reps',
  }, [
    '10 Yard Sprint',
    '20 Yard Sprint',
    '30 Yard Sprint',
    'Flying 10',
    'Flying 20',
    'Home to First',
    'First Step',
    'Lateral Shuffle',
    'Crossovers',
    'Sprint Starts',
  ]),

  ...group('Agility', {
    bucket: 'speed_agility',
    subcategory: 'Agility',
    bodyRegion: 'Full Body',
    movementPattern: 'Change of Direction',
    physicalQualities: ['Deceleration', 'Change of Direction'],
    baseballCorrelations: ['Defense', 'Baserunning', 'First Step'],
    relatedMetrics: ['pro_agility', 'athleticism_score'],
    equipment: 'Cones or ladder',
    defaultSets: 4,
    defaultReps: 1,
    defaultIntensity: 'High',
    workloadType: 'reps',
  }, [
    'Pro Agility',
    '5-10-5',
    'T Drill',
    'Cone Drill',
    'Ladder Drill',
    'Mirror Drill',
    'Reactive Drill',
  ]),

  ...group('Grip & Forearm', {
    bucket: 'strength',
    subcategory: 'Grip and Forearm',
    bodyRegion: 'Forearm',
    movementPattern: 'Grip',
    physicalQualities: ['Grip Strength', 'Forearm Capacity'],
    baseballCorrelations: ['Bat Control', 'Arm Care', 'Ball Control'],
    relatedMetrics: ['hand_strength', 'grip_strength_left', 'grip_strength_right'],
    equipment: 'Dumbbells, plates, towels, rice bucket',
    defaultSets: 3,
    defaultReps: 10,
    defaultIntensity: 'Moderate',
  }, [
    ['Grip Dynamometer', { workloadType: 'measurement', defaultSets: null, defaultReps: null, defaultIntensity: 'Low', equipment: 'Grip dynamometer' }],
    ['Farmer Carry', { movementPattern: 'Carry', defaultSets: 3, defaultReps: 1, defaultDistance: 40 }],
    'Plate Pinch',
    ['Towel Pull Ups', { relatedMetrics: ['pull_ups', 'hand_strength'] }],
    'Fat Grip Holds',
    'Wrist Curl',
    'Reverse Wrist Curl',
    ['Pronation', { bucket: 'arm_care', subcategory: 'Forearm Care', defaultIntensity: 'Low' }],
    ['Supination', { bucket: 'arm_care', subcategory: 'Forearm Care', defaultIntensity: 'Low' }],
    ['Rice Bucket', { bucket: 'arm_care', subcategory: 'Forearm Care', equipment: 'Rice bucket', defaultIntensity: 'Low' }],
  ]),

  ...group('Conditioning', {
    bucket: 'conditioning',
    subcategory: 'Aerobic',
    bodyRegion: 'Full Body',
    movementPattern: 'Energy System',
    physicalQualities: ['Work Capacity', 'Recovery Capacity'],
    baseballCorrelations: ['Practice Capacity', 'Between-Rep Recovery'],
    relatedMetrics: ['recovery_score', 'workload'],
    equipment: 'Open space or machine',
    defaultDurationSec: 600,
    defaultIntensity: 'Moderate',
    workloadType: 'time',
  }, [
    'Bike',
    'StairMaster',
    'Assault Bike',
    'Jog',
    'Tempo Runs',
    ['Sled Push', { subcategory: 'Anaerobic', movementPattern: 'Sled', defaultSets: 6, defaultDurationSec: null, defaultDistance: 20, defaultIntensity: 'High' }],
    ['Sled Pull', { subcategory: 'Anaerobic', movementPattern: 'Sled', defaultSets: 6, defaultDurationSec: null, defaultDistance: 20, defaultIntensity: 'High' }],
    ['Shuttle Runs', { subcategory: 'Anaerobic', movementPattern: 'Shuttle', defaultSets: 6, defaultDurationSec: null, defaultIntensity: 'High' }],
    ['Suicide Runs', { subcategory: 'Anaerobic', movementPattern: 'Shuttle', defaultSets: 4, defaultDurationSec: null, defaultIntensity: 'High' }],
    ['Hill Sprints', { subcategory: 'Anaerobic', movementPattern: 'Sprint', defaultSets: 6, defaultDurationSec: null, defaultIntensity: 'High' }],
  ]),

  ...group('Recovery', {
    bucket: 'recovery',
    subcategory: 'Recovery',
    bodyRegion: 'Full Body',
    movementPattern: 'Recovery',
    physicalQualities: ['Recovery', 'Readiness'],
    baseballCorrelations: ['Availability', 'Workload Tolerance'],
    relatedMetrics: ['recovery_score', 'sleep_quality', 'arm_care_compliance'],
    equipment: 'Recovery tools',
    defaultDurationSec: 300,
    defaultIntensity: 'Recovery',
    workloadType: 'time',
  }, [
    'Foam Roll',
    'Lacrosse Ball',
    'Stretch',
    'Ice Bath',
    'Contrast Bath',
    'Compression',
    'Walking Recovery',
    'Breathing',
    'Mobility Flow',
  ]),

  ...group('Mobility', {
    bucket: 'movement_prep',
    subcategory: 'Shoulder Mobility',
    bodyRegion: 'Mobility',
    movementPattern: 'Mobility',
    physicalQualities: ['Mobility', 'Range of Motion'],
    baseballCorrelations: ['Sequencing', 'Arm Health', 'Power Transfer'],
    relatedMetrics: ['mobility_score', 'shoulder_mobility_score', 'hip_mobility_score', 't_spine_mobility_score'],
    equipment: 'Bodyweight or bands',
    defaultSets: 1,
    defaultReps: 5,
    defaultIntensity: 'Low',
    workloadType: 'reps',
  }, [
    ['Shoulder Internal Rotation', { id: 'ex_mobility_shoulder_internal_rotation' }],
    ['Shoulder External Rotation', { id: 'ex_mobility_shoulder_external_rotation' }],
    'Total Motion',
    ['Shoulder Flexion', { id: 'ex_mobility_shoulder_flexion' }],
    ['Hip Internal Rotation', { subcategory: 'Hip Mobility', id: 'ex_mobility_hip_internal_rotation' }],
    ['Hip External Rotation', { subcategory: 'Hip Mobility', id: 'ex_mobility_hip_external_rotation' }],
    ['Hip Flexor', { subcategory: 'Hip Mobility' }],
    ['Hamstrings', { subcategory: 'Lower Body Mobility' }],
    ['Groin', { subcategory: 'Lower Body Mobility' }],
    ['Ankle Dorsiflexion', { subcategory: 'Lower Body Mobility' }],
    ['Thoracic Rotation', { subcategory: 'Spine Mobility' }],
    ['Neck CARs', { subcategory: 'Spine Mobility' }],
    ['Pelvic Rotation', { subcategory: 'Spine Mobility' }],
  ]),

  ...group('Throwing Development', {
    bucket: 'throwing',
    subcategory: 'Throwing Development',
    bodyRegion: 'Arm',
    movementPattern: 'Throwing',
    physicalQualities: ['Arm Speed', 'Throwing Capacity'],
    baseballCorrelations: ['Pitch Velocity', 'Throwing Velocity', 'Arm Strength'],
    relatedMetrics: ['pitch_velocity', 'long_toss_max_distance', 'weighted_ball_5oz_velocity'],
    equipment: 'Baseballs',
    defaultThrows: 20,
    defaultIntent: 70,
    defaultIntensity: 'Moderate',
    workloadType: 'throwing',
  }, [
    ['Catch Play', { defaultThrows: 25, defaultIntent: 60 }],
    ['Long Toss', { defaultThrows: 25, defaultIntent: 80, defaultDistance: 180, defaultIntensity: 'High' }],
    ['Pull Downs', { defaultThrows: 5, defaultIntent: 95, defaultIntensity: 'Maximum' }],
    ['Flat Ground', { bucket: 'pitching', subcategory: 'Pitching Development', defaultThrows: 15 }],
    ['Bullpen', { bucket: 'pitching', subcategory: 'Pitching Development', defaultThrows: 25, defaultIntensity: 'High' }],
    ['Recovery Throws', { defaultThrows: 20, defaultIntent: 40, defaultIntensity: 'Recovery' }],
    ['Weighted Balls', { equipment: 'Weighted balls', defaultThrows: 20, defaultIntent: 80 }],
    ['Pivot Pickoffs', { defaultThrows: 8, defaultIntent: 60 }],
    ['Reverse Throws', { equipment: 'Plyo or weighted ball', defaultThrows: 10, defaultIntent: 60 }],
  ]),

  ...group('Hitting Development', {
    bucket: 'hitting',
    subcategory: 'Hitting Development',
    bodyRegion: 'Hitter',
    movementPattern: 'Swing',
    physicalQualities: ['Bat Speed', 'Barrel Control', 'Contact Quality'],
    baseballCorrelations: ['Exit Velocity', 'Line Drive Rate', 'Swing Decisions'],
    relatedMetrics: ['average_exit_velocity', 'max_exit_velocity', 'hard_hit_percentage', 'line_drive_percentage'],
    equipment: 'Bats, balls, cage',
    defaultDurationSec: 600,
    defaultIntensity: 'Moderate',
    workloadType: 'time',
  }, [
    ['Tee Work', { equipment: 'Tee, balls, bat' }],
    ['Front Toss', { equipment: 'L-screen, balls, bat' }],
    ['Machine Work', { equipment: 'Pitching machine, balls, bat' }],
    ['Cage', { equipment: 'Cage, balls, bat' }],
    ['Scripted BP', { equipment: 'BP setup, balls, bat' }],
    ['Regular BP', { equipment: 'BP setup, balls, bat' }],
    ['Live AB', { defaultIntensity: 'High', equipment: 'Mound, catcher, hitter' }],
    ['Exit Velocity Testing', { equipment: 'Radar, tee/front toss', workloadType: 'measurement', relatedMetrics: ['max_exit_velocity', 'average_exit_velocity'] }],
  ]),
];

export const EXERCISE_LIBRARY_BY_BUCKET = EXERCISE_LIBRARY.reduce((acc, item) => {
  acc[item.bucket] = acc[item.bucket] || [];
  acc[item.bucket].push(item);
  return acc;
}, {});

export const EXERCISE_LIBRARY_GROUPS = [...new Set(EXERCISE_LIBRARY.map((item) => item.categoryGroup))];
